### ISSUE TITLE
Xcode9 / iOS11 / Swift4

### ISSUE THREAD

**Issue by keitaoouchi** [keitaoouchi/RxAudioVisual#5]
#### [AVAssetTrack](https://developer.apple.com/documentation/avfoundation/avassettrack?changes=latest_minor)

- mediaType: `String` --> `AVMediaType`

#### [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer?changes=latest_minor)

- isClosedCaptionDisplayEnabled: **Deprecated**

#### [AVPlayerLayer](https://developer.apple.com/documentation/avfoundation/avplayerlayer?changes=latest_minor)

- videoGravity: `String` --> `AVLayerVideoGravity`

### RxSwift

- [ ] waiting...

**Comment by numair** [comment]
@keitaoouchi any ideas on what it'd take to get the Example to run on Xcode 9b5?  I see a bunch of errors for SwiftyBeaver, assuming I can change the branch specified in the Cocoapod or something to get that to work, but haven't fully investigated yet.  Any major roadblocks that would prevent things from working, or is the list provided in your original issue post the entirety of what needs to get figured out?  Thanks for all of your help, and for putting together a great project!

**Comment by keitaoouchi** [comment]
Hi! @numair 
Thank you for your comment.
SwiftyBeaver (or some another logging frameworks written by Swift) is a major roadblock for Example project.

SwiftyBeaver seems to be planning to support Swift 4, but it seems that it has not started yet. I am not particular about SwiftyBeaver,  so I'm planning changing it to another framework written by obj-c.

I have not investigated RxSwift@swift4.0 or Xcode9b5, I will investigate them on the weekend!

Thx.

**Comment by numair** [comment]
Thanks for the follow-up, @keitaoouchi — your attention to this project is
truly commendable. I will also spend some time in the next day or two
seeing if I can strip out the SwiftyBeaver dependency and get things to
work.

**Comment by keitaoouchi** [comment]
Done.
