### ISSUE TITLE
Pod outdated

### ISSUE THREAD

**Issue by zishanj** [keitaoouchi/RxAudioVisual#9]
Please update the pod. It currently points to version 1.0.1 which requires RxSwift 3.4

**Comment by keitaoouchi** [comment]
Hi @zishanj.
Latest version of RxAudioVisual is `1.2.0`. 
Please check out the latest version, or `pod update RxAudioVisual --repo-update` in your terminal.

**Comment by zishanj** [comment]
I am receiving this again and again:

```
RxAudioVisual was resolved to 1.0.1, which depends on
      RxSwift (~> 3.4)
```

**Comment by zishanj** [comment]
I think the version 1.2.0 is not uploaded to Cocoapod yet. I have to add this line in pod file:

`pod 'RxAudioVisual', :git => "https://github.com/keitaoouchi/RxAudioVisual.git"`

**Comment by zishanj** [comment]
btw, RxSwift does not require minimum iOS to be 10.0 why this library requires?

**Comment by keitaoouchi** [comment]
I already uploaded latest version.
https://github.com/CocoaPods/Specs/commit/a4e6fd9ef1861eb1cc826c49d082dee43386cefd
~~http://cocoapods.org/pods/MarkdownView~~

Sorry, I don't have much time to support older version of iOS,
so if you need to support iOS 9.x please fork this and use it please.

**Comment by zishanj** [comment]
That link is related to `MarkdownView` not `RxAudioVisual`... :)

**Comment by keitaoouchi** [comment]
OH!
Wait a moments...

**Comment by keitaoouchi** [comment]
hm...???

```bash
pod trunk push --allow-warnings

[!] Found podspec `RxAudioVisual.podspec`
Updating spec repo `master`
Validating podspec
 -> RxAudioVisual (1.2.0)
    - WARN  | xcodebuild:  RxSwift/RxSwift/Schedulers/CurrentThreadScheduler.swift:54:17: warning: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead

[!] Unable to accept duplicate entry for: RxAudioVisual (1.2.0)
```

**Comment by keitaoouchi** [comment]
https://github.com/CocoaPods/Specs/tree/b03069e04941e815bd93d767088c9e037e5a8ef5/Specs/a/b/e/RxAudioVisual

**Comment by zishanj** [comment]
Can u do one favor plz? The iOS 10.0 requirement is due to the example app only, otherwise the RxAudioVisual lib can still work with  9.0.

**Comment by zishanj** [comment]
I had forked your repository but it will be difficult for me to make it upto date in parallel to your repo.

**Comment by keitaoouchi** [comment]
If this feature would possible, I may support...
https://discuss.bitrise.io/t/allow-xcode-testing-step-for-multiple-devices-operating-systems/147/6
